export const tableSchemas = {
  ciudades: {
    table: 'ciudades',
    id: 'id_ciudad',
    columns: ['nombre'],
  },
  colegios: {
    table: 'colegios',
    id: 'id_colegio',
    columns: ['nombre', 'direccion', 'telefono', 'id_ciudad'],
  },
  roles: {
    table: 'roles',
    id: 'id_rol',
    columns: ['nombre', 'descripcion'],
  },
  usuarios: {
    table: 'usuarios',
    id: 'id_usuario',
    columns: ['nombre', 'correo', 'contrasena', 'estado'],
  },
  usuarioRol: {
    table: 'usuario_rol',
    id: 'id_usuario_rol',
    columns: ['id_usuario', 'id_rol'],
  },
  bodegas: {
    table: 'bodegas',
    id: 'id_bodega',
    columns: ['nombre', 'ubicacion'],
  },
  libros: {
    table: 'libros',
    id: 'id_libro',
    columns: [
      'titulo',
      'isbn',
      'grado',
      'area',
      'stock',
      'codigo_qr',
      'autor',
      'descripcion',
      'precio_base',
      'foto_portada',
    ],
  },
  combos: {
    table: 'combos',
    id: 'id_combo',
    columns: ['nombre', 'descripcion'],
  },
  comboDetalle: {
    table: 'combo_detalle',
    id: 'id_combo_detalle',
    columns: ['id_combo', 'id_libro', 'cantidad'],
  },
  precioLibroColegioAnio: {
    table: 'precio_libro_colegio_anio',
    id: 'id_precio_libro',
    columns: ['id_libro', 'id_colegio', 'anio', 'precio'],
  },
  precioComboColegioAnio: {
    table: 'precio_combo_colegio_anio',
    id: 'id_precio_combo',
    columns: ['id_combo', 'id_colegio', 'anio', 'precio'],
  },
  pedidos: {
    table: 'pedidos',
    id: 'id_pedido',
    columns: ['fecha', 'id_colegio', 'id_usuario', 'total', 'estado'],
  },
  pedidoDetalle: {
    table: 'pedido_detalle',
    id: 'id_pedido_detalle',
    columns: [
      'id_pedido',
      'tipo_producto',
      'id_libro',
      'id_combo',
      'cantidad',
      'precio_unitario',
      'subtotal',
    ],
  },
  movimientoInventario: {
    table: 'movimiento_inventario',
    id: 'id_movimiento',
    columns: [
      'fecha',
      'tipo_movimiento',
      'id_bodega',
      'id_usuario',
      'total',
      'observacion',
    ],
  },
  movimientoDetalle: {
    table: 'movimiento_detalle',
    id: 'id_movimiento_detalle',
    columns: ['id_movimiento', 'id_libro', 'cantidad'],
  },
  logEscaneos: {
    table: 'log_escaneos',
    id: 'id_log_escaneo',
    columns: ['fecha_hora', 'id_usuario', 'id_libro', 'id_combo', 'resultado'],
  },
  despachos: {
    table: 'despachos',
    id: 'id_despacho',
    columns: [
      'fecha',
      'id_pedido',
      'id_usuario',
      'estado',
      'numero_remision',
      'observacion',
    ],
  },
  despachoDetalle: {
    table: 'despacho_detalle',
    id: 'id_despacho_detalle',
    columns: ['id_despacho', 'id_libro', 'cantidad'],
  },
  remisiones: {
    table: 'remisiones',
    id: 'id_remision',
    columns: [
      'id_despacho',
      'numero',
      'fecha_generacion',
      'id_usuario',
      'archivo_pdf',
      'estado',
    ],
  },
  devoluciones: {
    table: 'devoluciones',
    id: 'id_devolucion',
    columns: [
      'fecha',
      'id_pedido',
      'id_despacho',
      'id_usuario',
      'motivo',
      'reintegrar_inventario',
      'estado',
    ],
  },
  devolucionDetalle: {
    table: 'devolucion_detalle',
    id: 'id_devolucion_detalle',
    columns: [
      'id_devolucion',
      'id_libro',
      'id_combo',
      'cantidad',
      'estado_libro',
      'observacion',
    ],
  },
  historialActividad: {
    table: 'historial_actividad',
    id: 'id_actividad',
    columns: [
      'tipo',
      'titulo',
      'detalle',
      'id_usuario',
      'nombre_usuario',
      'rol_usuario',
      'fecha_hora',
      'tipo_entidad',
      'id_entidad',
      'nombre_entidad',
    ],
  },
};
